version: '3.4'

services:
  ecommerceproject:
    image: ecommerceproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:1234 --nothreading --noreload"]
    ports:
      - 1234:1234
      - 5678:5678
