# Generated by Django 4.0 on 2022-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connect',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
