# Generated by Django 4.0 on 2022-01-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_payment_order_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
